### ISSUE TITLE
Where is `lucadamico.android.calendar`

### ISSUE THREAD

**Issue by ianko** [trimethyl/trimethyl#22]
The Calendar requires this `lucadamico.android.calendar` module, but I couldn't find anywhere.

Can you guys provide the link to download it?

Thanks.

**Comment by Jei** [comment]
Here it is: https://marketplace.appcelerator.com/apps/93943
I also updated the link on the [Wiki page](https://github.com/trimethyl/trimethyl/wiki/Calendar)

**Comment by ianko** [comment]
Thank you. I forgot to check the Marketplace.

**Comment by Jei** [comment]
No problem.
It's unfortunate we have to use an external module for this part of Trimethyl, but it provides methods that are not (yet) supported by Titanium.
