### ISSUE TITLE
Missing Appcelerator Modules

### ISSUE THREAD

**Issue by Claymm** [trimethyl/trimethyl#30]
`appcelerator.encrypteddatabase` and `appcelerator.https` have now disappeared from https://github.com/appcelerator-modules.

Impossible to install this anymore. :(

**Comment by progress44** [comment]
These modules have never been open source. They're available for registered Appcelerator subscriptions. They recently made the Indie subscription free again and the modules are available for download with that subscription

**Comment by Claymm** [comment]
Hum… Sorry but I can’t seem to find them on here
<https://marketplace.appcelerator.com/home> either.


On 7 September 2017 at 19:01:19, Ani Sinanaj (notifications@github.com)
wrote:

These modules have never been open source. They're available for registered
Appcelerator subscriptions. They recently made the Indie subscription free
again and the modules are available for download with that subscription

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/trimethyl/trimethyl/issues/30#issuecomment-327876542>,
or mute the thread

**Comment by progress44** [comment]
After logging in go here https://platform.appcelerator.com. On the top right menu you have your user icon, click on it and on the drop-down menu click downloads. You'll find a few modules there, among others, HTTPS and encrypted database

**Comment by Topener** [comment]
`https` requires a pro subscription. You can see that here: http://docs.appcelerator.com/platform/latest/#!/api/Modules.Https
I don't know where to find `encrypteddatabase` so I guess it requires enterprise

**Comment by progress44** [comment]
It does say you need a pro subscription on the documentation but I've been able to download both with my indie account and I just tried it now and it works (**SQLite Database Encryption Module** is the name of the encrypted database module)

**Comment by Claymm** [comment]
Can you please share links?

**Comment by progress44** [comment]
I don't think it's appropriate since they require a subscription. Try asking on Slack (TiSlack) someone from Appcelerator can better help you with that

**Comment by Claymm** [comment]
I've got an Indie plan but I'm really struggling to find anything related to those two modules...

**Comment by progress44** [comment]
The url is https://platform.appcelerator.com/#/download
![screen shot 2017-09-08 at 11 17 47](https://user-images.githubusercontent.com/872842/30204919-791337f0-9487-11e7-8a21-c34a318acfbc.png)
![screen shot 2017-09-08 at 11 18 08](https://user-images.githubusercontent.com/872842/30204924-7c21e32e-9487-11e7-9fb6-202719f2022f.png)

**Comment by Claymm** [comment]
Nice one! Finally. This is really not obvious. Thanks.

**Comment by Topener** [comment]
@progress44 I would like to point out there is no appcelerator support on TiSlack. Sometimes they are there, but it is not an official appcelerator channel and it is community (me) run.

**Comment by progress44** [comment]
@Topener Yeah I know it's not official support, but someone from Appcelerator would be better suited to answer than me and as you say, sometimes they are there.
